@baseUrl = http://localhost:81

@contentType= application/json

### Sign UP
POST {{baseUrl}}/signup
Content-Type: {{contentType}}

{
 "email": "dev@dev.com.br",
 "password" : "!Password1",
 "passwordConfirmation": "!Password1"
}

### Sign In
POST {{baseUrl}}/signin
Content-Type: {{contentType}}

{
 "email": "dev@dev.com.br",
 "password" : "!Password1"
}
